apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../gbr-engine/k8s/bases
  - ../../web

images:
  - name: gbr-engine-web
    newName: gbr-engine-web
    newTag: latest
