apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbr-engine-web
  labels:
    app: gbr-engine-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gbr-engine-web
  template:
    metadata:
      labels:
        app: gbr-engine-web
    spec:
      containers:
        - name: web
          image: gbr-engine-web:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
