apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gbr-engine-web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: gbr-engine-web.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gbr-engine-web
                port:
                  number: 8080
