apiVersion: v1
kind: Service
metadata:
  name: gbr-engine-web
spec:
  type: LoadBalancer
  selector:
    app: gbr-engine-web
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
